platform :ios, '10.0'

target 'assa_ssibal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for assa_ssibal
  # Firebase
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

#progress bar


end
